# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ijgOCgwXn7ncU_s_F399EROA4WBm6o_
"""

from dataclasses import dataclass
import math
import json
from datetime import datetime


@dataclass
class ParkEnvironment:

    date: str
    # YYYY-MM-DD

    pollen_density: float
    # 粒/m³
    # 北京市区域背景花粉浓度

    green_area: float
    # 公园绿地面积
    # ha

    juniper_density: float
    # 棵/ha

    poplar_density: float
    # 棵/ha

    willow_density: float
    # 棵/ha

    wind_speed: float
    # m/s

    humidity: float
    # %

    rainfall_48h: float
    # mm

    sunlight_hours: float
    # h

    temperature: float
    # 摄氏度

    pm25: float
    # μg/m³

    uv_index: float
    # UVI

    consecutive_sunny_days: int
    # 天


# 基础工具函数

def clamp(
    value,
    minimum=0,
    maximum=100
):

    return max(
        minimum,
        min(value, maximum)
    )


def gaussian_score(
    value,
    optimal,
    sigma,
    amplitude=100
):

    score = amplitude * math.exp(
        -((value - optimal) ** 2) /
        (2 * sigma ** 2)
    )

    return clamp(score)


def logistic_score(
    value,
    midpoint,
    steepness,
    maximum=100
):

    score = maximum / (
        1 + math.exp(
            -steepness *
            (value - midpoint)
        )
    )

    return clamp(score)


def exponential_growth_score(
    value,
    rate=0.5,
    maximum=100
):

    score = maximum * (
        1 - math.exp(
            -rate * value
        )
    )

    return clamp(score)


# 月份距离函数

def circular_month_distance(
    month,
    peak_month
):

    diff = abs(
        month - peak_month
    )

    return min(
        diff,
        12 - diff
    )


# 季节活跃函数

def seasonal_factor(
    month,
    peak_month,
    sigma,
    baseline=0.0025,
    amplitude=0.94
):

    distance = (
        circular_month_distance(
            month,
            peak_month
        )
    )

    factor = baseline + (
        amplitude *
        math.exp(
            -(distance ** 2) /
            (2 * sigma ** 2)
        )
    )

    return factor


# 城市绿地蒿属估算模型

def estimate_artemisia_density(

    green_area
):
    ecological_density = (
        10 +
        42 *

        (
            1 -
            math.exp(
                -green_area / 18
            )
        )
    )
    management_decay = (
        1 -
        0.18 *
        (
            1 -
            math.exp(
                -green_area / 120
            )
        )
    )
    density = (
        ecological_density *
        management_decay
    )
    return density


# 城市绿地草本植物估算模型

def estimate_grass_density(

    green_area
):
    ecological_density = (
        32 +
        85 *
        (
            1 -
            math.exp(
                -green_area / 26
            )
        )
    )
    management_decay = (
        1 -
        0.10 *
        (
            1 -
            math.exp(
                -green_area / 160
            )
        )
    )
    density = (
        ecological_density *
        management_decay
    )
    return density


# 致敏植物丰度计算

def calculate_allergenic_abundance(
    env,
    month
):

    artemisia_density = (
        estimate_artemisia_density(
            env.green_area
        )
    )

    grass_density = (
        estimate_grass_density(
            env.green_area
        )
    )

    juniper_activity = seasonal_factor(
        month=month,
        peak_month=3.84,
        sigma=0.95
    )

    artemisia_activity = seasonal_factor(
        month=month,
        peak_month=9,
        sigma=1.3
    )

    poplar_activity = seasonal_factor(
        month=month,
        peak_month=4.1,
        sigma=1.1
    )

    willow_activity = seasonal_factor(
        month=month,
        peak_month=3.9,
        sigma=1.1
    )

    grass_activity = seasonal_factor(
        month=month,
        peak_month=8.7,
        sigma=1.3
    )

    weighted_sum = (

    env.juniper_density *
    1.09 *
    juniper_activity +

    artemisia_density *
    1.07 *
    artemisia_activity *
    artemisia_wind_multiplier(
        env.wind_speed
    ) +

    env.poplar_density *
    0.58 *
    poplar_activity +

    env.willow_density *
    0.50 *
    willow_activity +

    grass_density *
    0.52 *
    grass_activity *
    grass_wind_multiplier(
        env.wind_speed
    )
)

    return (
        weighted_sum,
        artemisia_density,
        grass_density
    )


# 局部植被增强函数

def local_density_multiplier(
    allergenic_abundance
):

    multiplier = (
        0.90 +
        0.70 *
        (
            1 -
            math.exp(
                -allergenic_abundance / 185
            )
        )
    )

    return multiplier

# 蒿属风速增强模型

def artemisia_wind_multiplier(
    wind_speed
):

    multiplier = (
        0.38 +
        0.82 *
        math.exp(
            -(
                (wind_speed - 1.5) ** 2
            ) /
            (
                2 * 1.3 ** 2
            )
        )
    )

    return multiplier

# 草本植物风速增强模型

def grass_wind_multiplier(
    wind_speed
):

    multiplier = (
        0.30 +
        0.88 *
        math.exp(
            -(
                (wind_speed - 2.2) ** 2
            ) /
            (
                2 * 1.35 ** 2
            )
        )
    )

    return multiplier

# 花粉暴露评分

def pollen_score(
    local_exposure
):

    return logistic_score(
        value=local_exposure,
        midpoint=24,
        steepness=0.158
    )


# 植被危险度评分

def plant_score(
    allergenic_abundance
):

    return logistic_score(
        value=allergenic_abundance,
        midpoint=185,
        steepness=0.018
    )


# 风速传播模型

def wind_score(
    wind_speed
):

    return gaussian_score(
        value=wind_speed,
        optimal=3.2,
        sigma=1.6,
        amplitude=72
    )


# 湿度影响模型

def humidity_score(
    humidity
):
    return gaussian_score(
        value=humidity,
        optimal=42,
        sigma=20,
        amplitude=77
    )


# 降雨抑制模型

def rainfall_score(
    rainfall_48h
):

    suppression = logistic_score(
        value=rainfall_48h,
        midpoint=6,
        steepness=0.20
    )

    return clamp(
        70 - suppression,
        0,
        100
    )


# 日照影响模型

def sunlight_score(
    hours
):

    return logistic_score(
        value=hours,
        midpoint=6,
        steepness=0.28
    )


# 温度影响模型

def temperature_score(
    temp
):

    return gaussian_score(
        value=temp,
        optimal=22,
        sigma=8
    )


# PM2.5模型

def pm25_score(
    pm25
):

    return logistic_score(
        value=pm25,
        midpoint=95,
        steepness=0.025
    )


# UV模型

def uv_score(
    uv
):

    return gaussian_score(
        value=uv,
        optimal=7,
        sigma=2.6,
        amplitude=52
    )


# 连续晴天模型

def sunny_days_score(
    days
):

    return exponential_growth_score(
        value=days,
        rate=0.14,
        maximum=62
    )


# 风险计算函数

def calculate_risk(
    env: ParkEnvironment
):

    date_obj = datetime.strptime(
        env.date,
        "%Y-%m-%d"
    )

    current_month = (
        date_obj.month +
        (date_obj.day - 1) / 30
    )
    (
        allergenic_abundance,
        artemisia_density,
        grass_density
    ) = calculate_allergenic_abundance(
        env,
        current_month
    )

    density_multiplier = (
        local_density_multiplier(
            allergenic_abundance
        )
    )

    local_exposure = (
        env.pollen_density *
        density_multiplier
    )

    P = pollen_score(
        local_exposure
    )

    A = plant_score(
        allergenic_abundance
    )

    juniper_component = (
        env.juniper_density *
        1.22 *
        seasonal_factor(
            current_month,
            3.84,
            0.95
        )
    )

    artemisia_component = (
        artemisia_density *
        1.05 *
        seasonal_factor(
            current_month,
            9,
            1.3
        )
     *
    artemisia_wind_multiplier(
        env.wind_speed
        )
    )

    poplar_component = (
        env.poplar_density *
        0.50 *
        seasonal_factor(
            current_month,
            4.1,
            1.1
        )
    )

    willow_component = (
        env.willow_density *
        0.42 *
        seasonal_factor(
            current_month,
            3.9,
            1.1
        )
    )

    grass_component = (
    grass_density *
    0.45 *
    seasonal_factor(
        current_month,
        8.7,
        1.3
    ) *
    grass_wind_multiplier(
        env.wind_speed
    )
)

    total_component = max(
        juniper_component +
        artemisia_component +
        poplar_component +
        willow_component +
        grass_component,
        1e-6
    )

    pollen_load = (
        0.85 * P +
        0.15 * A
    )

    allergen_subscores = {

        "刺柏": round(
            pollen_load *
            (
                juniper_component /
                total_component
            ),
            2
        ),

        "蒿属": round(
            pollen_load *
            (
                artemisia_component /
                total_component
            ),
            2
        ),

        "杨树": round(
            pollen_load *
            (
                poplar_component /
                total_component
            ),
            2
        ),

        "柳树": round(
            pollen_load *
            (
                willow_component /
                total_component
            ),
            2
        ),

        "草本植物": round(
            pollen_load *
            (
                grass_component /
                total_component
            ),
            2
        )
    }

    W = wind_score(
        env.wind_speed
    )

    S = sunlight_score(
        env.sunlight_hours
    )

    T = temperature_score(
        env.temperature
    )

    weather_transport = (
        0.45 * W +
        0.25 * S +
        0.30 * T
    )

    H = humidity_score(
        env.humidity
    )

    C = sunny_days_score(
        env.consecutive_sunny_days
    )

    R = rainfall_score(
        env.rainfall_48h
    )

    atmospheric_retention = (
        0.38 * H +
        0.14 * C +
        0.48 * R
    )

    M = pm25_score(
        env.pm25
    )

    inflammatory_multiplier = (
        1 +
        0.1 *
        (M / 100)
    )

    U = uv_score(
        env.uv_index
    )

    bioactivity_factor = (
        0.52 * T +
        0.14 * U +
        0.34 * S
    )

    raw_exposure = (
    pollen_load
    *
    (
        0.72 +
        0.28 *
        weather_transport / 100
    )
    *
    (
        0.82 +
        0.18 *
        atmospheric_retention / 100
    )
)

    base_exposure = 100 * (
        1 - math.exp(
            -raw_exposure / 56
        )
    )

    biologically_active_exposure = (
        0.94 * base_exposure +
        0.06 * bioactivity_factor
    )

    inflammatory_risk = (
        biologically_active_exposure *
        inflammatory_multiplier
    )

    if (
        env.wind_speed > 8 and
        env.humidity < 40
    ):
        inflammatory_risk += 2.5

    if (
        env.humidity > 80 and
        env.wind_speed > 6
    ):
        inflammatory_risk += 1.5

    if env.rainfall_48h > 25:
        inflammatory_risk -= 7

    if env.pm25 > 120:
        inflammatory_risk += 2.5

    if env.uv_index > 10:
        inflammatory_risk += 1

    if (
        1 <= env.rainfall_48h <= 4 and
        env.humidity > 70
    ):
        inflammatory_risk += 3

    total_risk = clamp(
        inflammatory_risk
    )

    if total_risk < 15:

        level = "安全"

    elif total_risk < 35:

        level = "轻度风险"

    elif total_risk < 55:

        level = "中度风险"

    elif total_risk < 75:

        level = "高风险"

    else:

        level = "极高风险"

    if total_risk >= 80:

        recommendation = (
            "不建议过敏患者进入园区"
        )

    elif total_risk >= 60:

        recommendation = (
            "建议佩戴N95口罩并减少停留"
        )

    elif total_risk >= 40:

        recommendation = (
            "敏感人群建议谨慎活动"
        )

    else:

        recommendation = (
            "可正常活动"
        )

    factors = {

        "局部花粉暴露": P,

        "植被危险度": A,

        "风速扩散": W,

        "湿度影响": H,

        "降雨情况": R,

        "日照": S,

        "温度": T,

        "PM2.5": M,

        "UV": U,

        "连续晴天": C
    }

    sorted_factors = sorted(
        factors.items(),
        key=lambda x: x[1],
        reverse=True
    )

    top_risks = sorted_factors[:3]

    return {

        "风险评分":
            round(total_risk, 2),

        "风险等级":
            level,

        "活动建议":
            recommendation,

        "估算蒿属密度":
            round(
                artemisia_density,
                2
            ),

        "估算草本密度":
            round(
                grass_density,
                2
            ),

        "局部植被增强系数":
            round(
                density_multiplier,
                3
            ),

        "局部真实花粉暴露":
            round(
                local_exposure,
                2
            ),

        "致敏植物加权丰度":
            round(
                allergenic_abundance,
                2
            ),

        "过敏源小分":
            allergen_subscores,

        "主要风险因素":
            top_risks,

        "详细指标": {

            "局部花粉暴露":
                round(P, 2),

            "植被危险度":
                round(A, 2),

            "天气传播":
                round(
                    weather_transport,
                    2
                ),

            "空气滞留":
                round(
                    atmospheric_retention,
                    2
                ),

            "花粉生物活性":
                round(
                    bioactivity_factor,
                    2
                ),

            "基础暴露":
                round(
                    base_exposure,
                    2
                ),

            "生物活性暴露":
                round(
                    biologically_active_exposure,
                    2
                ),

            "炎症增强系数":
                round(
                    inflammatory_multiplier,
                    3
                )
        }
    }


# 示例数据

example = ParkEnvironment(

    date="2026-09-05",

    pollen_density=46,

    green_area=120,

    juniper_density=2,

    poplar_density=3,

    willow_density=2,

    wind_speed=7.1,

    humidity=20,

    rainfall_48h=0,

    sunlight_hours=11.2,

    temperature=30,

    pm25=148,

    uv_index=9,

    consecutive_sunny_days=11
)

result = calculate_risk(
    example
)

print(
    "\n"
    "╔════════════════════════════════╗\n"
    "║      北京公园过敏风险评估报告      ║\n"
    "╚════════════════════════════════╝\n"
)

print(
    f"风险评分：{result['风险评分']}/100"
)

print(
    f"风险等级：{result['风险等级']}"
)

print(
    f"活动建议：{result['活动建议']}\n"
)

print(
    "【核心指标】"
)

print(
    f"估算蒿属覆盖指数：{result['估算蒿属密度']} AU"
)

print(
    f"估算草本覆盖指数：{result['估算草本密度']} AU"
)

print(
    f"局部植被增强系数：{result['局部植被增强系数']}"
)

print(
    f"局部真实花粉暴露：{result['局部真实花粉暴露']} 粒/m³"
)

print(
    f"致敏植物加权丰度：{result['致敏植物加权丰度']}\n"
)

print(
    "【过敏源贡献评分】"
)

for name, score in result["过敏源小分"].items():

    print(
        f"{name:<8} {score:>6}"
    )

print()

print(
    "【主要风险因素】"
)


for index, item in enumerate(
    result["主要风险因素"],
    start=1
):

    factor_name = item[0]
    factor_score = round(item[1], 2)

    print(
        f"{index}. {factor_name:<10} {factor_score}"
    )

print()

print(
    "【详细指标】"
)

for key, value in result["详细指标"].items():

    print(
        f"{key:<12} : {value}"
    )

"""# **Reference**

**Wind Speed & Climate**

Damialis, A., Traidl-Hoffmann, C., & Treudler, R. (2019). Climate change and pollen allergies. In Allergy Frontiers: Epigenetics, Allergens and Risk Factors (pp. 47–66). Springer. https://doi.org/10.1007/978-4-431-55908-3_3

Rojo, J., Picornell, A., Oteros, J., Werchan, M., Werchan, B., Bergmann, K. C., Schmidt-Weber, C. B., Buters, J., & Damialis, A. (2021). Consequences of climate change on airborne pollen in Europe. Aerobiologia, 37(4), 639–651. https://doi.org/10.1007/s10453-021-09723-0

Sofiev, M., Bergmann, K.-C., & the WHO Collaborating Centre for Air Quality Management and Air Pollution Control. (2013). Allergenic pollen: A review of the production, release, distribution and health impacts. In Allergenic Pollen (pp. 1–27). Springer. https://doi.org/10.1007/978-94-007-4881-1

Skjøth, C. A., Sommer, J., Brandt, J., Hvidberg, M., Geels, C., Hansen, K. M., Hertel, O., Frohn, L. M., Christensen, J. H., & Andersen, U. V. (2008). Copenhagen—a significant source of birch (Betula) pollen? International Journal of Biometeorology, 52(6), 453–462. https://doi.org/10.1007/s00484-007-0139-y

Burbach, G. J., Heinzerling, L. M., Edenharter, G., Bachert, C., Bindslev-Jensen, C., Bonini, S., Bousquet, J., Bousquet-Rouanet, L., Bousquet, P. J., Brunekreef, B., Burney, P., Canonica, G. W., Darsow, U., Demoly, P., Durham, S., Fokkens, W. J., Giavi, S., Gjomarkaj, M., Gramiccioni, C., … Zuberbier, T. (2009). GA²LEN skin test study II: Clinical relevance of inhalant allergen sensitizations in Europe. Allergy, 64(10), 1507–1515. https://doi.org/10.1111/j.1398-9995.2009.02089.x

Cariñanos, P., Adinolfi, C., Díaz de la Guardia, C., De Linares, C., & Casares-Porcel, M. (2014). Characterization of allergen emission sources in urban areas. Journal of Environmental Quality, 43(1), 244–252. https://doi.org/10.2134/jeq2011.0471

**Humidity & Precipitation**

Emberlin, J., Mullins, J., Corden, J., Millington, W., Brooke, M., Savage, M., & Jones, S. (1997). The trend to earlier birch pollen seasons in the UK: A biotic response to changes in weather conditions? Grana, 36(1), 29–33. https://doi.org/10.1080/00173139709362586

Galán, C., Alcázar, P., Cariñanos, P., García-Mozo, H., & Domínguez-Vilches, E. (2007). Meteorological factors affecting daily Urticaceae pollen counts in southwest Spain. International Journal of Biometeorology, 51(3), 145–152. https://doi.org/10.1007/s00484-006-0054-5

Kasprzyk, I. (2008). Non-native Ambrosia pollen in the atmosphere of Rzeszów (SE Poland); evaluation of the effect of weather conditions on daily concentrations and starting dates of the pollen season. International Journal of Biometeorology, 52(5), 341–351. https://doi.org/10.1007/s00484-007-0124-5

Oteros, J., García-Mozo, H., Vázquez, L., Mestre, A., Domínguez-Vilches, E., & Galán, C. (2013). Modelling olive pollen intensity in the Mediterranean region through analysis of emission sources and atmospheric circulation. Agricultural and Forest Meteorology, 179, 145–155. https://doi.org/10.1016/j.agrformet.2013.05.004

Rantio-Lehtimäki, A., Kauppinen, P., & Koivikko, A. (1994). Airborne birch pollen antigens in different particles. Clinical & Experimental Allergy, 24(1), 23–28. https://doi.org/10.1111/j.1365-2222.1994.tb00911.x

Zink, K., Kaufmann, P., Petitpierre, B., Broennimann, O., Guisan, A., & Gentili, R. (2012). Climate change impacts on the spatial distribution of allergenic plants and pollen seasons in Switzerland. Advances in Meteorology, 2012, 1–11. https://doi.org/10.1155/2012/518397

**Air Pollution and Inflammation**

Diaz-Sanchez, D., Tsien, A., Fleming, J., & Saxon, A. (1997). Combined diesel exhaust particulate and ragweed allergen challenge markedly enhances human in vivo nasal ragweed-specific IgE and skews cytokine production to a T helper cell 2-type pattern. Journal of Immunology, 158(5), 2406–2413.

Kelly, F. J., & Fussell, J. C. (2011). Air pollution and airway disease. Clinical & Experimental Allergy, 41(8), 1059–1071. https://doi.org/10.1111/j.1365-2222.2011.03776.x

Liu, L., Poon, R., Chen, L., Frescura, A.-M., Montuschi, P., Ciabattoni, G., Wheeler, A., & Dales, R. (2009). Acute effects of air pollution on pulmonary function, airway inflammation, and oxidative stress in asthmatic children. Environmental Health Perspectives, 117(4), 668–674. https://doi.org/10.1289/ehp.11813

Motta, A. C., Marliere, M., Peltre, G., Sterenberg, P. A., & Lacroix, G. (2006). Traffic-related air pollutants induce the release of allergen-containing cytoplasmic granules from grass pollen. International Archives of Allergy and Immunology, 139(4), 294–298. https://doi.org/10.1159/000091122

Behrendt, H., Becker, W. M., Fritzsche, C., Sliwa-Tomczok, W., Tomczok, J., Friedrichs, K. H., Ring, J., & Huss-Marp, J. (1997). Air pollution and allergy: Experimental studies on modulation of allergen release from pollen by air pollutants. International Archives of Allergy and Immunology, 113(1–3), 69–74. https://doi.org/10.1159/000237532

D’Amato, G., Cecchi, L., D’Amato, M., & Liccardi, G. (2010). Urban air pollution and climate change as environmental risk factors of respiratory allergy: An update. Journal of Investigational Allergology and Clinical Immunology, 20(2), 95–102.

**UV and Temperature**

Beggs, P. J. (2004). Impacts of climate change on aeroallergens: Past and future. Clinical & Experimental Allergy, 34(10), 1507–1513. https://doi.org/10.1111/j.1365-2222.2004.02061.x

Cecchi, L., D’Amato, G., Ayres, J. G., Galán, C., Forastiere, F., Forsberg, B., Gerritsen, J., Nunes, C., Behrendt, H., Akdis, C., Dahl, R., & Annesi-Maesano, I. (2010). Projections of the effects of climate change on allergic asthma: The contribution of aerobiology. Allergy, 65(9), 1073–1081. https://doi.org/10.1111/j.1398-9995.2010.02423.x

García-Mozo, H. (2017). Poaceae pollen as the leading aeroallergen worldwide: A review. Allergy, 72(12), 1849–1858. https://doi.org/10.1111/all.13210

Ziska, L. H., Epstein, P. R., & Schlesinger, W. H. (2009). Rising CO2, climate change, and public health: Exploring the links to plant biology. Environmental Health Perspectives, 117(2), 155–158. https://doi.org/10.1289/ehp.11501

Lake, I. R., Jones, N. R., Agnew, M., Goodess, C. M., Giorgi, F., Hamaoui-Laguel, L., Semenov, M. A., Solomon, F., Storkey, J., Vautard, R., & Epstein, M. M. (2017). Climate change and future pollen allergy in Europe. Environmental Health Perspectives, 125(3), 385–391. https://doi.org/10.1289/EHP173

Anderegg, W. R. L., Abatzoglou, J. T., Anderegg, L. D. L., Bielory, L., Kinney, P. L., & Ziska, L. (2021). Anthropogenic climate change is worsening North American pollen seasons. Proceedings of the National Academy of Sciences, 118(7), e2013284118. https://doi.org/10.1073/pnas.2013284118

**Artemisia / Weed Pollen Specific Studies**

Taramarcaz, P., Lambelet, C., Clot, B., Keimer, C., & Hauser, C. (2005). Ragweed (Ambrosia) progression and its health risks: Will Switzerland resist this invasion? Swiss Medical Weekly, 135(37–38), 538–548.

Jato, V., Rodríguez-Rajo, F. J., Alcázar, P., De Nuntiis, P., Galán, C., & Mandrioli, P. (2006). May the definition of pollen season influence aerobiological results? Aerobiologia, 22(1), 13–25. https://doi.org/10.1007/s10453-005-9011-x

Smith, M., Cecchi, L., Skjøth, C. A., Karrer, G., & Šikoparija, B. (2013). Common ragweed: A threat to environmental health in Europe. Environment International, 61, 115–126. https://doi.org/10.1016/j.envint.2013.08.005

Zhang, Y., Bielory, L., Mi, Z., Cai, T., Robock, A., Georgopoulos, P., & Gong, D. (2015). Allergenic pollen season variations in the past two decades under changing climate in the United States. Global Change Biology, 21(4), 1581–1589. https://doi.org/10.1111/gcb.12755
"""